# -*- coding: utf-8 -*-
"""Untitled14.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QIzkvuflk-6dXVsPirNu0N1XBJJWMp6-
"""

from google.colab.patches import cv2_imshow
import cv2

picture1=cv2.imread("0374a53ec1d24242792e31d2e6ec02eb.jpg")
picture2=cv2.imread("Ronaldo-Madrid-debut-1024x459.png")
picture3=cv2.imread("640px-Cristiano_Ronaldo_playing_for_Al_Nassr_FC_against_Persepolis,_Septembe.jpg")

cv2_imshow(picture1)
cv2_imshow(picture2)
cv2_imshow(picture3)


color1=cv2.cvtColor(picture1,cv2.COLOR_BGR2GRAY)
cv2_imshow(color1)
color2=cv2.cvtColor(picture2,cv2.COLOR_BGR2GRAY)
cv2_imshow(color2)
color3=cv2.cvtColor(picture3,cv2.COLOR_BGR2GRAY)
cv2_imshow(color3)